/*
    Feature Branch - Assigned to Akhilesh
    Added add method by Akhilesh
    Name: TestDemo
    Name: feature/sub

    Created By: Akhilesh Kulkarni
 Salesforce-Development
*/
public with sharing class TestDemo {
    public TestDemo() {

    }

    public Integer add(Integer a,Integer b)
    {
        return a + b;

    }
    public Integer sub(Integer a,Integer b)
    {
        return a - b;

    }
}
